import Head from 'next/head'
import Image from 'next/image'
import {postsList, PostListItem} from "../data/posts";
import {getPage, getPages, PageData, PageItem} from "../data/pages";
import Nav from "../components/Navigation/Nav";
import {getNavigation, Navigation} from "../data/navigation";
import {GetStaticPaths} from 'next'
import Page from "../components/Page/Page";

type Props = {
	posts: PostListItem[]
	page: PageData
	navigation: Navigation
}

export default function Home(props) {
	return (
		<div>
			<Head>
				<title>siembrabosques</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>


			<h1>
				<a href="https://nextjs.org">siembrabosques</a>
			</h1>
			<Nav navigation={props.navigation}/>

			<Page page={props.page}/>

			<h2>posts:</h2>
			<ul>
				{
					props.posts.map(post => <li key={post.slug}><a href={`/post/${post.slug}`}>{post.slug}</a></li>)
				}
			</ul>
			<footer>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
				</a>
			</footer>
		</div>
	)
}


export async function getStaticProps({params}): Promise<{ props: Props }> {
	const posts = await postsList()
	const navigation = await getNavigation()
	const pages = await getPages()
	const matchingPage = pages.find(page => page.slug === params.page)

	const page = await getPage(matchingPage.id)

	const props: Props = {
		posts,
		navigation,
		page
	}

	return {props}
}

export const getStaticPaths: GetStaticPaths = async () => {
	const pages = await getPages()

	return {
		fallback: false,
		paths: pages.map(page => {
			return {
				params: {
					id: page.id,
					page: page.slug
				}
			}
		})
	}
}

